// Generated by gencpp from file task1/CheckpointProcessor.msg
// DO NOT EDIT!


#ifndef TASK1_MESSAGE_CHECKPOINTPROCESSOR_H
#define TASK1_MESSAGE_CHECKPOINTPROCESSOR_H

#include <ros/service_traits.h>


#include <task1/CheckpointProcessorRequest.h>
#include <task1/CheckpointProcessorResponse.h>


namespace task1
{

struct CheckpointProcessor
{

typedef CheckpointProcessorRequest Request;
typedef CheckpointProcessorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckpointProcessor
} // namespace task1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task1::CheckpointProcessor > {
  static const char* value()
  {
    return "af3f94b765997022c6ac0867e7797cba";
  }

  static const char* value(const ::task1::CheckpointProcessor&) { return value(); }
};

template<>
struct DataType< ::task1::CheckpointProcessor > {
  static const char* value()
  {
    return "task1/CheckpointProcessor";
  }

  static const char* value(const ::task1::CheckpointProcessor&) { return value(); }
};


// service_traits::MD5Sum< ::task1::CheckpointProcessorRequest> should match 
// service_traits::MD5Sum< ::task1::CheckpointProcessor > 
template<>
struct MD5Sum< ::task1::CheckpointProcessorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task1::CheckpointProcessor >::value();
  }
  static const char* value(const ::task1::CheckpointProcessorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task1::CheckpointProcessorRequest> should match 
// service_traits::DataType< ::task1::CheckpointProcessor > 
template<>
struct DataType< ::task1::CheckpointProcessorRequest>
{
  static const char* value()
  {
    return DataType< ::task1::CheckpointProcessor >::value();
  }
  static const char* value(const ::task1::CheckpointProcessorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task1::CheckpointProcessorResponse> should match 
// service_traits::MD5Sum< ::task1::CheckpointProcessor > 
template<>
struct MD5Sum< ::task1::CheckpointProcessorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task1::CheckpointProcessor >::value();
  }
  static const char* value(const ::task1::CheckpointProcessorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task1::CheckpointProcessorResponse> should match 
// service_traits::DataType< ::task1::CheckpointProcessor > 
template<>
struct DataType< ::task1::CheckpointProcessorResponse>
{
  static const char* value()
  {
    return DataType< ::task1::CheckpointProcessor >::value();
  }
  static const char* value(const ::task1::CheckpointProcessorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK1_MESSAGE_CHECKPOINTPROCESSOR_H
