// Generated by gencpp from file task1/Checkpoint_res.msg
// DO NOT EDIT!


#ifndef TASK1_MESSAGE_CHECKPOINT_RES_H
#define TASK1_MESSAGE_CHECKPOINT_RES_H

#include <ros/service_traits.h>


#include <task1/Checkpoint_resRequest.h>
#include <task1/Checkpoint_resResponse.h>


namespace task1
{

struct Checkpoint_res
{

typedef Checkpoint_resRequest Request;
typedef Checkpoint_resResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Checkpoint_res
} // namespace task1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task1::Checkpoint_res > {
  static const char* value()
  {
    return "f7b43fb4c3dc044f1ecb1f843f952947";
  }

  static const char* value(const ::task1::Checkpoint_res&) { return value(); }
};

template<>
struct DataType< ::task1::Checkpoint_res > {
  static const char* value()
  {
    return "task1/Checkpoint_res";
  }

  static const char* value(const ::task1::Checkpoint_res&) { return value(); }
};


// service_traits::MD5Sum< ::task1::Checkpoint_resRequest> should match 
// service_traits::MD5Sum< ::task1::Checkpoint_res > 
template<>
struct MD5Sum< ::task1::Checkpoint_resRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task1::Checkpoint_res >::value();
  }
  static const char* value(const ::task1::Checkpoint_resRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task1::Checkpoint_resRequest> should match 
// service_traits::DataType< ::task1::Checkpoint_res > 
template<>
struct DataType< ::task1::Checkpoint_resRequest>
{
  static const char* value()
  {
    return DataType< ::task1::Checkpoint_res >::value();
  }
  static const char* value(const ::task1::Checkpoint_resRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task1::Checkpoint_resResponse> should match 
// service_traits::MD5Sum< ::task1::Checkpoint_res > 
template<>
struct MD5Sum< ::task1::Checkpoint_resResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task1::Checkpoint_res >::value();
  }
  static const char* value(const ::task1::Checkpoint_resResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task1::Checkpoint_resResponse> should match 
// service_traits::DataType< ::task1::Checkpoint_res > 
template<>
struct DataType< ::task1::Checkpoint_resResponse>
{
  static const char* value()
  {
    return DataType< ::task1::Checkpoint_res >::value();
  }
  static const char* value(const ::task1::Checkpoint_resResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK1_MESSAGE_CHECKPOINT_RES_H
