// Generated by gencpp from file task2/ColourClassificationSrv.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_COLOURCLASSIFICATIONSRV_H
#define TASK2_MESSAGE_COLOURCLASSIFICATIONSRV_H

#include <ros/service_traits.h>


#include <task2/ColourClassificationSrvRequest.h>
#include <task2/ColourClassificationSrvResponse.h>


namespace task2
{

struct ColourClassificationSrv
{

typedef ColourClassificationSrvRequest Request;
typedef ColourClassificationSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ColourClassificationSrv
} // namespace task2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task2::ColourClassificationSrv > {
  static const char* value()
  {
    return "caf04d413f9e4daef949309d687bb7a1";
  }

  static const char* value(const ::task2::ColourClassificationSrv&) { return value(); }
};

template<>
struct DataType< ::task2::ColourClassificationSrv > {
  static const char* value()
  {
    return "task2/ColourClassificationSrv";
  }

  static const char* value(const ::task2::ColourClassificationSrv&) { return value(); }
};


// service_traits::MD5Sum< ::task2::ColourClassificationSrvRequest> should match 
// service_traits::MD5Sum< ::task2::ColourClassificationSrv > 
template<>
struct MD5Sum< ::task2::ColourClassificationSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task2::ColourClassificationSrv >::value();
  }
  static const char* value(const ::task2::ColourClassificationSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::ColourClassificationSrvRequest> should match 
// service_traits::DataType< ::task2::ColourClassificationSrv > 
template<>
struct DataType< ::task2::ColourClassificationSrvRequest>
{
  static const char* value()
  {
    return DataType< ::task2::ColourClassificationSrv >::value();
  }
  static const char* value(const ::task2::ColourClassificationSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task2::ColourClassificationSrvResponse> should match 
// service_traits::MD5Sum< ::task2::ColourClassificationSrv > 
template<>
struct MD5Sum< ::task2::ColourClassificationSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task2::ColourClassificationSrv >::value();
  }
  static const char* value(const ::task2::ColourClassificationSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::ColourClassificationSrvResponse> should match 
// service_traits::DataType< ::task2::ColourClassificationSrv > 
template<>
struct DataType< ::task2::ColourClassificationSrvResponse>
{
  static const char* value()
  {
    return DataType< ::task2::ColourClassificationSrv >::value();
  }
  static const char* value(const ::task2::ColourClassificationSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK2_MESSAGE_COLOURCLASSIFICATIONSRV_H
