// Generated by gencpp from file task2/FeatureBuilderRequest.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_FEATUREBUILDERREQUEST_H
#define TASK2_MESSAGE_FEATUREBUILDERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task2
{
template <class ContainerAllocator>
struct FeatureBuilderRequest_
{
  typedef FeatureBuilderRequest_<ContainerAllocator> Type;

  FeatureBuilderRequest_()
    : flg(0)  {
    }
  FeatureBuilderRequest_(const ContainerAllocator& _alloc)
    : flg(0)  {
  (void)_alloc;
    }



   typedef int64_t _flg_type;
  _flg_type flg;





  typedef boost::shared_ptr< ::task2::FeatureBuilderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task2::FeatureBuilderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FeatureBuilderRequest_

typedef ::task2::FeatureBuilderRequest_<std::allocator<void> > FeatureBuilderRequest;

typedef boost::shared_ptr< ::task2::FeatureBuilderRequest > FeatureBuilderRequestPtr;
typedef boost::shared_ptr< ::task2::FeatureBuilderRequest const> FeatureBuilderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task2::FeatureBuilderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task2::FeatureBuilderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace task2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'task2': ['/home/dkalsan/ris-alpha/workspaces/tasks/src/task2/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::task2::FeatureBuilderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task2::FeatureBuilderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task2::FeatureBuilderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task2::FeatureBuilderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::FeatureBuilderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::FeatureBuilderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task2::FeatureBuilderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8e58b690355adaa882da8790bb22595";
  }

  static const char* value(const ::task2::FeatureBuilderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8e58b690355adaaULL;
  static const uint64_t static_value2 = 0x882da8790bb22595ULL;
};

template<class ContainerAllocator>
struct DataType< ::task2::FeatureBuilderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task2/FeatureBuilderRequest";
  }

  static const char* value(const ::task2::FeatureBuilderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task2::FeatureBuilderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 flg\n\
";
  }

  static const char* value(const ::task2::FeatureBuilderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task2::FeatureBuilderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FeatureBuilderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task2::FeatureBuilderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task2::FeatureBuilderRequest_<ContainerAllocator>& v)
  {
    s << indent << "flg: ";
    Printer<int64_t>::stream(s, indent + "  ", v.flg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK2_MESSAGE_FEATUREBUILDERREQUEST_H
