// Generated by gencpp from file task2/GetRingColor.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_GETRINGCOLOR_H
#define TASK2_MESSAGE_GETRINGCOLOR_H

#include <ros/service_traits.h>


#include <task2/GetRingColorRequest.h>
#include <task2/GetRingColorResponse.h>


namespace task2
{

struct GetRingColor
{

typedef GetRingColorRequest Request;
typedef GetRingColorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetRingColor
} // namespace task2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task2::GetRingColor > {
  static const char* value()
  {
    return "f1520819364d5ba5d943a48edb027a19";
  }

  static const char* value(const ::task2::GetRingColor&) { return value(); }
};

template<>
struct DataType< ::task2::GetRingColor > {
  static const char* value()
  {
    return "task2/GetRingColor";
  }

  static const char* value(const ::task2::GetRingColor&) { return value(); }
};


// service_traits::MD5Sum< ::task2::GetRingColorRequest> should match 
// service_traits::MD5Sum< ::task2::GetRingColor > 
template<>
struct MD5Sum< ::task2::GetRingColorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task2::GetRingColor >::value();
  }
  static const char* value(const ::task2::GetRingColorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::GetRingColorRequest> should match 
// service_traits::DataType< ::task2::GetRingColor > 
template<>
struct DataType< ::task2::GetRingColorRequest>
{
  static const char* value()
  {
    return DataType< ::task2::GetRingColor >::value();
  }
  static const char* value(const ::task2::GetRingColorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task2::GetRingColorResponse> should match 
// service_traits::MD5Sum< ::task2::GetRingColor > 
template<>
struct MD5Sum< ::task2::GetRingColorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task2::GetRingColor >::value();
  }
  static const char* value(const ::task2::GetRingColorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::GetRingColorResponse> should match 
// service_traits::DataType< ::task2::GetRingColor > 
template<>
struct DataType< ::task2::GetRingColorResponse>
{
  static const char* value()
  {
    return DataType< ::task2::GetRingColor >::value();
  }
  static const char* value(const ::task2::GetRingColorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK2_MESSAGE_GETRINGCOLOR_H
