// Generated by gencpp from file task2/GetRingColorRequest.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_GETRINGCOLORREQUEST_H
#define TASK2_MESSAGE_GETRINGCOLORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task2
{
template <class ContainerAllocator>
struct GetRingColorRequest_
{
  typedef GetRingColorRequest_<ContainerAllocator> Type;

  GetRingColorRequest_()
    : start(0)  {
    }
  GetRingColorRequest_(const ContainerAllocator& _alloc)
    : start(0)  {
  (void)_alloc;
    }



   typedef int64_t _start_type;
  _start_type start;





  typedef boost::shared_ptr< ::task2::GetRingColorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task2::GetRingColorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetRingColorRequest_

typedef ::task2::GetRingColorRequest_<std::allocator<void> > GetRingColorRequest;

typedef boost::shared_ptr< ::task2::GetRingColorRequest > GetRingColorRequestPtr;
typedef boost::shared_ptr< ::task2::GetRingColorRequest const> GetRingColorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task2::GetRingColorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task2::GetRingColorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace task2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'task2': ['/home/miha/Desktop/ris-alpha/workspaces/tasks/src/task2/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::task2::GetRingColorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task2::GetRingColorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task2::GetRingColorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task2::GetRingColorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::GetRingColorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task2::GetRingColorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task2::GetRingColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f3cefc2a81c697b38bf59faba5b0cd16";
  }

  static const char* value(const ::task2::GetRingColorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf3cefc2a81c697b3ULL;
  static const uint64_t static_value2 = 0x8bf59faba5b0cd16ULL;
};

template<class ContainerAllocator>
struct DataType< ::task2::GetRingColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task2/GetRingColorRequest";
  }

  static const char* value(const ::task2::GetRingColorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task2::GetRingColorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 start\n\
";
  }

  static const char* value(const ::task2::GetRingColorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task2::GetRingColorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetRingColorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task2::GetRingColorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task2::GetRingColorRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    Printer<int64_t>::stream(s, indent + "  ", v.start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK2_MESSAGE_GETRINGCOLORREQUEST_H
