// Generated by gencpp from file task2/RingApproachPoint.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_RINGAPPROACHPOINT_H
#define TASK2_MESSAGE_RINGAPPROACHPOINT_H

#include <ros/service_traits.h>


#include <task2/RingApproachPointRequest.h>
#include <task2/RingApproachPointResponse.h>


namespace task2
{

struct RingApproachPoint
{

typedef RingApproachPointRequest Request;
typedef RingApproachPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RingApproachPoint
} // namespace task2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task2::RingApproachPoint > {
  static const char* value()
  {
    return "a0a873596cba774a4f04b2ea2ebf3221";
  }

  static const char* value(const ::task2::RingApproachPoint&) { return value(); }
};

template<>
struct DataType< ::task2::RingApproachPoint > {
  static const char* value()
  {
    return "task2/RingApproachPoint";
  }

  static const char* value(const ::task2::RingApproachPoint&) { return value(); }
};


// service_traits::MD5Sum< ::task2::RingApproachPointRequest> should match 
// service_traits::MD5Sum< ::task2::RingApproachPoint > 
template<>
struct MD5Sum< ::task2::RingApproachPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task2::RingApproachPoint >::value();
  }
  static const char* value(const ::task2::RingApproachPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::RingApproachPointRequest> should match 
// service_traits::DataType< ::task2::RingApproachPoint > 
template<>
struct DataType< ::task2::RingApproachPointRequest>
{
  static const char* value()
  {
    return DataType< ::task2::RingApproachPoint >::value();
  }
  static const char* value(const ::task2::RingApproachPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task2::RingApproachPointResponse> should match 
// service_traits::MD5Sum< ::task2::RingApproachPoint > 
template<>
struct MD5Sum< ::task2::RingApproachPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task2::RingApproachPoint >::value();
  }
  static const char* value(const ::task2::RingApproachPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::RingApproachPointResponse> should match 
// service_traits::DataType< ::task2::RingApproachPoint > 
template<>
struct DataType< ::task2::RingApproachPointResponse>
{
  static const char* value()
  {
    return DataType< ::task2::RingApproachPoint >::value();
  }
  static const char* value(const ::task2::RingApproachPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK2_MESSAGE_RINGAPPROACHPOINT_H
