// Generated by gencpp from file task2/ValidRegionsMap.msg
// DO NOT EDIT!


#ifndef TASK2_MESSAGE_VALIDREGIONSMAP_H
#define TASK2_MESSAGE_VALIDREGIONSMAP_H

#include <ros/service_traits.h>


#include <task2/ValidRegionsMapRequest.h>
#include <task2/ValidRegionsMapResponse.h>


namespace task2
{

struct ValidRegionsMap
{

typedef ValidRegionsMapRequest Request;
typedef ValidRegionsMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ValidRegionsMap
} // namespace task2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task2::ValidRegionsMap > {
  static const char* value()
  {
    return "ba554fc9d98703ab25e4d0b10b456967";
  }

  static const char* value(const ::task2::ValidRegionsMap&) { return value(); }
};

template<>
struct DataType< ::task2::ValidRegionsMap > {
  static const char* value()
  {
    return "task2/ValidRegionsMap";
  }

  static const char* value(const ::task2::ValidRegionsMap&) { return value(); }
};


// service_traits::MD5Sum< ::task2::ValidRegionsMapRequest> should match 
// service_traits::MD5Sum< ::task2::ValidRegionsMap > 
template<>
struct MD5Sum< ::task2::ValidRegionsMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task2::ValidRegionsMap >::value();
  }
  static const char* value(const ::task2::ValidRegionsMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::ValidRegionsMapRequest> should match 
// service_traits::DataType< ::task2::ValidRegionsMap > 
template<>
struct DataType< ::task2::ValidRegionsMapRequest>
{
  static const char* value()
  {
    return DataType< ::task2::ValidRegionsMap >::value();
  }
  static const char* value(const ::task2::ValidRegionsMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task2::ValidRegionsMapResponse> should match 
// service_traits::MD5Sum< ::task2::ValidRegionsMap > 
template<>
struct MD5Sum< ::task2::ValidRegionsMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task2::ValidRegionsMap >::value();
  }
  static const char* value(const ::task2::ValidRegionsMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task2::ValidRegionsMapResponse> should match 
// service_traits::DataType< ::task2::ValidRegionsMap > 
template<>
struct DataType< ::task2::ValidRegionsMapResponse>
{
  static const char* value()
  {
    return DataType< ::task2::ValidRegionsMap >::value();
  }
  static const char* value(const ::task2::ValidRegionsMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK2_MESSAGE_VALIDREGIONSMAP_H
