// Generated by gencpp from file alpha1/SumIntegersRequest.msg
// DO NOT EDIT!


#ifndef ALPHA1_MESSAGE_SUMINTEGERSREQUEST_H
#define ALPHA1_MESSAGE_SUMINTEGERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alpha1
{
template <class ContainerAllocator>
struct SumIntegersRequest_
{
  typedef SumIntegersRequest_<ContainerAllocator> Type;

  SumIntegersRequest_()
    : numbers()  {
    }
  SumIntegersRequest_(const ContainerAllocator& _alloc)
    : numbers(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _numbers_type;
  _numbers_type numbers;





  typedef boost::shared_ptr< ::alpha1::SumIntegersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alpha1::SumIntegersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SumIntegersRequest_

typedef ::alpha1::SumIntegersRequest_<std::allocator<void> > SumIntegersRequest;

typedef boost::shared_ptr< ::alpha1::SumIntegersRequest > SumIntegersRequestPtr;
typedef boost::shared_ptr< ::alpha1::SumIntegersRequest const> SumIntegersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alpha1::SumIntegersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alpha1::SumIntegersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alpha1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'alpha1': ['/home/miha/Desktop/ris-alpha/workspaces/introduction-to-ROS/src/alpha1/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alpha1::SumIntegersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alpha1::SumIntegersRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpha1::SumIntegersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpha1::SumIntegersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpha1::SumIntegersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpha1::SumIntegersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alpha1::SumIntegersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3dc0ed8c2332c3d3ba50a96ed8318f1c";
  }

  static const char* value(const ::alpha1::SumIntegersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3dc0ed8c2332c3d3ULL;
  static const uint64_t static_value2 = 0xba50a96ed8318f1cULL;
};

template<class ContainerAllocator>
struct DataType< ::alpha1::SumIntegersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alpha1/SumIntegersRequest";
  }

  static const char* value(const ::alpha1::SumIntegersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alpha1::SumIntegersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] numbers\n\
";
  }

  static const char* value(const ::alpha1::SumIntegersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alpha1::SumIntegersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.numbers);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumIntegersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alpha1::SumIntegersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alpha1::SumIntegersRequest_<ContainerAllocator>& v)
  {
    s << indent << "numbers[]" << std::endl;
    for (size_t i = 0; i < v.numbers.size(); ++i)
    {
      s << indent << "  numbers[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.numbers[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALPHA1_MESSAGE_SUMINTEGERSREQUEST_H
