// Generated by gencpp from file exercise4/ForwardRange.msg
// DO NOT EDIT!


#ifndef EXERCISE4_MESSAGE_FORWARDRANGE_H
#define EXERCISE4_MESSAGE_FORWARDRANGE_H

#include <ros/service_traits.h>


#include <exercise4/ForwardRangeRequest.h>
#include <exercise4/ForwardRangeResponse.h>


namespace exercise4
{

struct ForwardRange
{

typedef ForwardRangeRequest Request;
typedef ForwardRangeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ForwardRange
} // namespace exercise4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exercise4::ForwardRange > {
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::exercise4::ForwardRange&) { return value(); }
};

template<>
struct DataType< ::exercise4::ForwardRange > {
  static const char* value()
  {
    return "exercise4/ForwardRange";
  }

  static const char* value(const ::exercise4::ForwardRange&) { return value(); }
};


// service_traits::MD5Sum< ::exercise4::ForwardRangeRequest> should match 
// service_traits::MD5Sum< ::exercise4::ForwardRange > 
template<>
struct MD5Sum< ::exercise4::ForwardRangeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exercise4::ForwardRange >::value();
  }
  static const char* value(const ::exercise4::ForwardRangeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise4::ForwardRangeRequest> should match 
// service_traits::DataType< ::exercise4::ForwardRange > 
template<>
struct DataType< ::exercise4::ForwardRangeRequest>
{
  static const char* value()
  {
    return DataType< ::exercise4::ForwardRange >::value();
  }
  static const char* value(const ::exercise4::ForwardRangeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exercise4::ForwardRangeResponse> should match 
// service_traits::MD5Sum< ::exercise4::ForwardRange > 
template<>
struct MD5Sum< ::exercise4::ForwardRangeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exercise4::ForwardRange >::value();
  }
  static const char* value(const ::exercise4::ForwardRangeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise4::ForwardRangeResponse> should match 
// service_traits::DataType< ::exercise4::ForwardRange > 
template<>
struct DataType< ::exercise4::ForwardRangeResponse>
{
  static const char* value()
  {
    return DataType< ::exercise4::ForwardRange >::value();
  }
  static const char* value(const ::exercise4::ForwardRangeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXERCISE4_MESSAGE_FORWARDRANGE_H
