// Generated by gencpp from file exercise4/ForwardRangeResponse.msg
// DO NOT EDIT!


#ifndef EXERCISE4_MESSAGE_FORWARDRANGERESPONSE_H
#define EXERCISE4_MESSAGE_FORWARDRANGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise4
{
template <class ContainerAllocator>
struct ForwardRangeResponse_
{
  typedef ForwardRangeResponse_<ContainerAllocator> Type;

  ForwardRangeResponse_()
    : distance(0.0)  {
    }
  ForwardRangeResponse_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::exercise4::ForwardRangeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise4::ForwardRangeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ForwardRangeResponse_

typedef ::exercise4::ForwardRangeResponse_<std::allocator<void> > ForwardRangeResponse;

typedef boost::shared_ptr< ::exercise4::ForwardRangeResponse > ForwardRangeResponsePtr;
typedef boost::shared_ptr< ::exercise4::ForwardRangeResponse const> ForwardRangeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise4::ForwardRangeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise4::ForwardRangeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exercise4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exercise4::ForwardRangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise4::ForwardRangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise4::ForwardRangeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise4::ForwardRangeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise4::ForwardRangeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise4::ForwardRangeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise4::ForwardRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::exercise4::ForwardRangeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise4::ForwardRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise4/ForwardRangeResponse";
  }

  static const char* value(const ::exercise4::ForwardRangeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise4::ForwardRangeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n\
";
  }

  static const char* value(const ::exercise4::ForwardRangeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise4::ForwardRangeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForwardRangeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise4::ForwardRangeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::exercise4::ForwardRangeResponse_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE4_MESSAGE_FORWARDRANGERESPONSE_H
