// Generated by gencpp from file exercise4/ForwardRangeRequest.msg
// DO NOT EDIT!


#ifndef EXERCISE4_MESSAGE_FORWARDRANGEREQUEST_H
#define EXERCISE4_MESSAGE_FORWARDRANGEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace exercise4
{
template <class ContainerAllocator>
struct ForwardRangeRequest_
{
  typedef ForwardRangeRequest_<ContainerAllocator> Type;

  ForwardRangeRequest_()
    {
    }
  ForwardRangeRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::exercise4::ForwardRangeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::exercise4::ForwardRangeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ForwardRangeRequest_

typedef ::exercise4::ForwardRangeRequest_<std::allocator<void> > ForwardRangeRequest;

typedef boost::shared_ptr< ::exercise4::ForwardRangeRequest > ForwardRangeRequestPtr;
typedef boost::shared_ptr< ::exercise4::ForwardRangeRequest const> ForwardRangeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::exercise4::ForwardRangeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::exercise4::ForwardRangeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace exercise4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::exercise4::ForwardRangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::exercise4::ForwardRangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise4::ForwardRangeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::exercise4::ForwardRangeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise4::ForwardRangeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::exercise4::ForwardRangeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::exercise4::ForwardRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::exercise4::ForwardRangeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::exercise4::ForwardRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "exercise4/ForwardRangeRequest";
  }

  static const char* value(const ::exercise4::ForwardRangeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::exercise4::ForwardRangeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::exercise4::ForwardRangeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::exercise4::ForwardRangeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForwardRangeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::exercise4::ForwardRangeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::exercise4::ForwardRangeRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // EXERCISE4_MESSAGE_FORWARDRANGEREQUEST_H
