// Generated by gencpp from file alpha2/TurtleManagerResponse.msg
// DO NOT EDIT!


#ifndef ALPHA2_MESSAGE_TURTLEMANAGERRESPONSE_H
#define ALPHA2_MESSAGE_TURTLEMANAGERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace alpha2
{
template <class ContainerAllocator>
struct TurtleManagerResponse_
{
  typedef TurtleManagerResponse_<ContainerAllocator> Type;

  TurtleManagerResponse_()
    : lastmovement()  {
    }
  TurtleManagerResponse_(const ContainerAllocator& _alloc)
    : lastmovement(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _lastmovement_type;
  _lastmovement_type lastmovement;





  typedef boost::shared_ptr< ::alpha2::TurtleManagerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::alpha2::TurtleManagerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleManagerResponse_

typedef ::alpha2::TurtleManagerResponse_<std::allocator<void> > TurtleManagerResponse;

typedef boost::shared_ptr< ::alpha2::TurtleManagerResponse > TurtleManagerResponsePtr;
typedef boost::shared_ptr< ::alpha2::TurtleManagerResponse const> TurtleManagerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::alpha2::TurtleManagerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::alpha2::TurtleManagerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace alpha2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::alpha2::TurtleManagerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::alpha2::TurtleManagerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpha2::TurtleManagerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::alpha2::TurtleManagerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpha2::TurtleManagerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::alpha2::TurtleManagerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::alpha2::TurtleManagerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "499ad2ae7415e189266ffdfc8162bf10";
  }

  static const char* value(const ::alpha2::TurtleManagerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x499ad2ae7415e189ULL;
  static const uint64_t static_value2 = 0x266ffdfc8162bf10ULL;
};

template<class ContainerAllocator>
struct DataType< ::alpha2::TurtleManagerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "alpha2/TurtleManagerResponse";
  }

  static const char* value(const ::alpha2::TurtleManagerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::alpha2::TurtleManagerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string lastmovement\n\
";
  }

  static const char* value(const ::alpha2::TurtleManagerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::alpha2::TurtleManagerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lastmovement);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleManagerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::alpha2::TurtleManagerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::alpha2::TurtleManagerResponse_<ContainerAllocator>& v)
  {
    s << indent << "lastmovement: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.lastmovement);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALPHA2_MESSAGE_TURTLEMANAGERRESPONSE_H
