(cl:defpackage task1-msg
  (:use )
  (:export
   "<CHECKPOINTPROCESSORRESPONSE>"
   "CHECKPOINTPROCESSORRESPONSE"
   "<CHECKPOINTS>"
   "CHECKPOINTS"
   "<ELLIPSEDATA>"
   "ELLIPSEDATA"
   "<SCANFLAG>"
   "SCANFLAG"
  ))

