(cl:defpackage task2-srv
  (:use )
  (:export
   "TERMINALAPPROACH"
   "<TERMINALAPPROACH-REQUEST>"
   "TERMINALAPPROACH-REQUEST"
   "<TERMINALAPPROACH-RESPONSE>"
   "TERMINALAPPROACH-RESPONSE"
   "VALIDREGIONSMAP"
   "<VALIDREGIONSMAP-REQUEST>"
   "VALIDREGIONSMAP-REQUEST"
   "<VALIDREGIONSMAP-RESPONSE>"
   "VALIDREGIONSMAP-RESPONSE"
  ))

