(cl:defpackage task2-srv
  (:use )
  (:export
   "GETRINGCOLOR"
   "<GETRINGCOLOR-REQUEST>"
   "GETRINGCOLOR-REQUEST"
   "<GETRINGCOLOR-RESPONSE>"
   "GETRINGCOLOR-RESPONSE"
   "RINGAPPROACHPOINT"
   "<RINGAPPROACHPOINT-REQUEST>"
   "RINGAPPROACHPOINT-REQUEST"
   "<RINGAPPROACHPOINT-RESPONSE>"
   "RINGAPPROACHPOINT-RESPONSE"
   "TERMINALAPPROACH"
   "<TERMINALAPPROACH-REQUEST>"
   "TERMINALAPPROACH-REQUEST"
   "<TERMINALAPPROACH-RESPONSE>"
   "TERMINALAPPROACH-RESPONSE"
   "VALIDREGIONSMAP"
   "<VALIDREGIONSMAP-REQUEST>"
   "VALIDREGIONSMAP-REQUEST"
   "<VALIDREGIONSMAP-RESPONSE>"
   "VALIDREGIONSMAP-RESPONSE"
  ))

