// Generated by gencpp from file task3/Checkpoint_res.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_CHECKPOINT_RES_H
#define TASK3_MESSAGE_CHECKPOINT_RES_H

#include <ros/service_traits.h>


#include <task3/Checkpoint_resRequest.h>
#include <task3/Checkpoint_resResponse.h>


namespace task3
{

struct Checkpoint_res
{

typedef Checkpoint_resRequest Request;
typedef Checkpoint_resResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Checkpoint_res
} // namespace task3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3::Checkpoint_res > {
  static const char* value()
  {
    return "164415de33c55ff5b8477a9721394803";
  }

  static const char* value(const ::task3::Checkpoint_res&) { return value(); }
};

template<>
struct DataType< ::task3::Checkpoint_res > {
  static const char* value()
  {
    return "task3/Checkpoint_res";
  }

  static const char* value(const ::task3::Checkpoint_res&) { return value(); }
};


// service_traits::MD5Sum< ::task3::Checkpoint_resRequest> should match 
// service_traits::MD5Sum< ::task3::Checkpoint_res > 
template<>
struct MD5Sum< ::task3::Checkpoint_resRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3::Checkpoint_res >::value();
  }
  static const char* value(const ::task3::Checkpoint_resRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::Checkpoint_resRequest> should match 
// service_traits::DataType< ::task3::Checkpoint_res > 
template<>
struct DataType< ::task3::Checkpoint_resRequest>
{
  static const char* value()
  {
    return DataType< ::task3::Checkpoint_res >::value();
  }
  static const char* value(const ::task3::Checkpoint_resRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3::Checkpoint_resResponse> should match 
// service_traits::MD5Sum< ::task3::Checkpoint_res > 
template<>
struct MD5Sum< ::task3::Checkpoint_resResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3::Checkpoint_res >::value();
  }
  static const char* value(const ::task3::Checkpoint_resResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::Checkpoint_resResponse> should match 
// service_traits::DataType< ::task3::Checkpoint_res > 
template<>
struct DataType< ::task3::Checkpoint_resResponse>
{
  static const char* value()
  {
    return DataType< ::task3::Checkpoint_res >::value();
  }
  static const char* value(const ::task3::Checkpoint_resResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_MESSAGE_CHECKPOINT_RES_H
