// Generated by gencpp from file task3/ColourClassificationSrv.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_COLOURCLASSIFICATIONSRV_H
#define TASK3_MESSAGE_COLOURCLASSIFICATIONSRV_H

#include <ros/service_traits.h>


#include <task3/ColourClassificationSrvRequest.h>
#include <task3/ColourClassificationSrvResponse.h>


namespace task3
{

struct ColourClassificationSrv
{

typedef ColourClassificationSrvRequest Request;
typedef ColourClassificationSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ColourClassificationSrv
} // namespace task3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3::ColourClassificationSrv > {
  static const char* value()
  {
    return "caf04d413f9e4daef949309d687bb7a1";
  }

  static const char* value(const ::task3::ColourClassificationSrv&) { return value(); }
};

template<>
struct DataType< ::task3::ColourClassificationSrv > {
  static const char* value()
  {
    return "task3/ColourClassificationSrv";
  }

  static const char* value(const ::task3::ColourClassificationSrv&) { return value(); }
};


// service_traits::MD5Sum< ::task3::ColourClassificationSrvRequest> should match 
// service_traits::MD5Sum< ::task3::ColourClassificationSrv > 
template<>
struct MD5Sum< ::task3::ColourClassificationSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3::ColourClassificationSrv >::value();
  }
  static const char* value(const ::task3::ColourClassificationSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::ColourClassificationSrvRequest> should match 
// service_traits::DataType< ::task3::ColourClassificationSrv > 
template<>
struct DataType< ::task3::ColourClassificationSrvRequest>
{
  static const char* value()
  {
    return DataType< ::task3::ColourClassificationSrv >::value();
  }
  static const char* value(const ::task3::ColourClassificationSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3::ColourClassificationSrvResponse> should match 
// service_traits::MD5Sum< ::task3::ColourClassificationSrv > 
template<>
struct MD5Sum< ::task3::ColourClassificationSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3::ColourClassificationSrv >::value();
  }
  static const char* value(const ::task3::ColourClassificationSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::ColourClassificationSrvResponse> should match 
// service_traits::DataType< ::task3::ColourClassificationSrv > 
template<>
struct DataType< ::task3::ColourClassificationSrvResponse>
{
  static const char* value()
  {
    return DataType< ::task3::ColourClassificationSrv >::value();
  }
  static const char* value(const ::task3::ColourClassificationSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_MESSAGE_COLOURCLASSIFICATIONSRV_H
