// Generated by gencpp from file task3/CylinderLocator.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_CYLINDERLOCATOR_H
#define TASK3_MESSAGE_CYLINDERLOCATOR_H

#include <ros/service_traits.h>


#include <task3/CylinderLocatorRequest.h>
#include <task3/CylinderLocatorResponse.h>


namespace task3
{

struct CylinderLocator
{

typedef CylinderLocatorRequest Request;
typedef CylinderLocatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CylinderLocator
} // namespace task3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3::CylinderLocator > {
  static const char* value()
  {
    return "7b497188d656d59d92c0ddf8ac50fe8a";
  }

  static const char* value(const ::task3::CylinderLocator&) { return value(); }
};

template<>
struct DataType< ::task3::CylinderLocator > {
  static const char* value()
  {
    return "task3/CylinderLocator";
  }

  static const char* value(const ::task3::CylinderLocator&) { return value(); }
};


// service_traits::MD5Sum< ::task3::CylinderLocatorRequest> should match 
// service_traits::MD5Sum< ::task3::CylinderLocator > 
template<>
struct MD5Sum< ::task3::CylinderLocatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3::CylinderLocator >::value();
  }
  static const char* value(const ::task3::CylinderLocatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::CylinderLocatorRequest> should match 
// service_traits::DataType< ::task3::CylinderLocator > 
template<>
struct DataType< ::task3::CylinderLocatorRequest>
{
  static const char* value()
  {
    return DataType< ::task3::CylinderLocator >::value();
  }
  static const char* value(const ::task3::CylinderLocatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3::CylinderLocatorResponse> should match 
// service_traits::MD5Sum< ::task3::CylinderLocator > 
template<>
struct MD5Sum< ::task3::CylinderLocatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3::CylinderLocator >::value();
  }
  static const char* value(const ::task3::CylinderLocatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::CylinderLocatorResponse> should match 
// service_traits::DataType< ::task3::CylinderLocator > 
template<>
struct DataType< ::task3::CylinderLocatorResponse>
{
  static const char* value()
  {
    return DataType< ::task3::CylinderLocator >::value();
  }
  static const char* value(const ::task3::CylinderLocatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_MESSAGE_CYLINDERLOCATOR_H
