// Generated by gencpp from file task3/CylinderLocation.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_CYLINDERLOCATION_H
#define TASK3_MESSAGE_CYLINDERLOCATION_H

#include <ros/service_traits.h>


#include <task3/CylinderLocationRequest.h>
#include <task3/CylinderLocationResponse.h>


namespace task3
{

struct CylinderLocation
{

typedef CylinderLocationRequest Request;
typedef CylinderLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CylinderLocation
} // namespace task3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3::CylinderLocation > {
  static const char* value()
  {
    return "449ac22520dbd7a67ea7d1766a88f2a4";
  }

  static const char* value(const ::task3::CylinderLocation&) { return value(); }
};

template<>
struct DataType< ::task3::CylinderLocation > {
  static const char* value()
  {
    return "task3/CylinderLocation";
  }

  static const char* value(const ::task3::CylinderLocation&) { return value(); }
};


// service_traits::MD5Sum< ::task3::CylinderLocationRequest> should match 
// service_traits::MD5Sum< ::task3::CylinderLocation > 
template<>
struct MD5Sum< ::task3::CylinderLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3::CylinderLocation >::value();
  }
  static const char* value(const ::task3::CylinderLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::CylinderLocationRequest> should match 
// service_traits::DataType< ::task3::CylinderLocation > 
template<>
struct DataType< ::task3::CylinderLocationRequest>
{
  static const char* value()
  {
    return DataType< ::task3::CylinderLocation >::value();
  }
  static const char* value(const ::task3::CylinderLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3::CylinderLocationResponse> should match 
// service_traits::MD5Sum< ::task3::CylinderLocation > 
template<>
struct MD5Sum< ::task3::CylinderLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3::CylinderLocation >::value();
  }
  static const char* value(const ::task3::CylinderLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::CylinderLocationResponse> should match 
// service_traits::DataType< ::task3::CylinderLocation > 
template<>
struct DataType< ::task3::CylinderLocationResponse>
{
  static const char* value()
  {
    return DataType< ::task3::CylinderLocation >::value();
  }
  static const char* value(const ::task3::CylinderLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_MESSAGE_CYLINDERLOCATION_H
