// Generated by gencpp from file task3/DigitDetector.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_DIGITDETECTOR_H
#define TASK3_MESSAGE_DIGITDETECTOR_H

#include <ros/service_traits.h>


#include <task3/DigitDetectorRequest.h>
#include <task3/DigitDetectorResponse.h>


namespace task3
{

struct DigitDetector
{

typedef DigitDetectorRequest Request;
typedef DigitDetectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DigitDetector
} // namespace task3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3::DigitDetector > {
  static const char* value()
  {
    return "64fdfdf2315ce0489e0badef6a400485";
  }

  static const char* value(const ::task3::DigitDetector&) { return value(); }
};

template<>
struct DataType< ::task3::DigitDetector > {
  static const char* value()
  {
    return "task3/DigitDetector";
  }

  static const char* value(const ::task3::DigitDetector&) { return value(); }
};


// service_traits::MD5Sum< ::task3::DigitDetectorRequest> should match 
// service_traits::MD5Sum< ::task3::DigitDetector > 
template<>
struct MD5Sum< ::task3::DigitDetectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3::DigitDetector >::value();
  }
  static const char* value(const ::task3::DigitDetectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::DigitDetectorRequest> should match 
// service_traits::DataType< ::task3::DigitDetector > 
template<>
struct DataType< ::task3::DigitDetectorRequest>
{
  static const char* value()
  {
    return DataType< ::task3::DigitDetector >::value();
  }
  static const char* value(const ::task3::DigitDetectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3::DigitDetectorResponse> should match 
// service_traits::MD5Sum< ::task3::DigitDetector > 
template<>
struct MD5Sum< ::task3::DigitDetectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3::DigitDetector >::value();
  }
  static const char* value(const ::task3::DigitDetectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::DigitDetectorResponse> should match 
// service_traits::DataType< ::task3::DigitDetector > 
template<>
struct DataType< ::task3::DigitDetectorResponse>
{
  static const char* value()
  {
    return DataType< ::task3::DigitDetector >::value();
  }
  static const char* value(const ::task3::DigitDetectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_MESSAGE_DIGITDETECTOR_H
