// Generated by gencpp from file task3/MapDetector.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_MAPDETECTOR_H
#define TASK3_MESSAGE_MAPDETECTOR_H

#include <ros/service_traits.h>


#include <task3/MapDetectorRequest.h>
#include <task3/MapDetectorResponse.h>


namespace task3
{

struct MapDetector
{

typedef MapDetectorRequest Request;
typedef MapDetectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapDetector
} // namespace task3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3::MapDetector > {
  static const char* value()
  {
    return "5c0167ecd7748962f1d9e21ddb0b0dae";
  }

  static const char* value(const ::task3::MapDetector&) { return value(); }
};

template<>
struct DataType< ::task3::MapDetector > {
  static const char* value()
  {
    return "task3/MapDetector";
  }

  static const char* value(const ::task3::MapDetector&) { return value(); }
};


// service_traits::MD5Sum< ::task3::MapDetectorRequest> should match 
// service_traits::MD5Sum< ::task3::MapDetector > 
template<>
struct MD5Sum< ::task3::MapDetectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3::MapDetector >::value();
  }
  static const char* value(const ::task3::MapDetectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::MapDetectorRequest> should match 
// service_traits::DataType< ::task3::MapDetector > 
template<>
struct DataType< ::task3::MapDetectorRequest>
{
  static const char* value()
  {
    return DataType< ::task3::MapDetector >::value();
  }
  static const char* value(const ::task3::MapDetectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3::MapDetectorResponse> should match 
// service_traits::MD5Sum< ::task3::MapDetector > 
template<>
struct MD5Sum< ::task3::MapDetectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3::MapDetector >::value();
  }
  static const char* value(const ::task3::MapDetectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::MapDetectorResponse> should match 
// service_traits::DataType< ::task3::MapDetector > 
template<>
struct DataType< ::task3::MapDetectorResponse>
{
  static const char* value()
  {
    return DataType< ::task3::MapDetector >::value();
  }
  static const char* value(const ::task3::MapDetectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_MESSAGE_MAPDETECTOR_H
