// Generated by gencpp from file task3/ReconfigParamsRequest.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_RECONFIGPARAMSREQUEST_H
#define TASK3_MESSAGE_RECONFIGPARAMSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task3
{
template <class ContainerAllocator>
struct ReconfigParamsRequest_
{
  typedef ReconfigParamsRequest_<ContainerAllocator> Type;

  ReconfigParamsRequest_()
    : param_name()
    , param_val(0.0)  {
    }
  ReconfigParamsRequest_(const ContainerAllocator& _alloc)
    : param_name(_alloc)
    , param_val(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _param_name_type;
  _param_name_type param_name;

   typedef double _param_val_type;
  _param_val_type param_val;





  typedef boost::shared_ptr< ::task3::ReconfigParamsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task3::ReconfigParamsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ReconfigParamsRequest_

typedef ::task3::ReconfigParamsRequest_<std::allocator<void> > ReconfigParamsRequest;

typedef boost::shared_ptr< ::task3::ReconfigParamsRequest > ReconfigParamsRequestPtr;
typedef boost::shared_ptr< ::task3::ReconfigParamsRequest const> ReconfigParamsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task3::ReconfigParamsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task3::ReconfigParamsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace task3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'task3': ['/home/dkalsan/ris-alpha/workspaces/tasks/src/task3/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::task3::ReconfigParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3::ReconfigParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task3::ReconfigParamsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task3::ReconfigParamsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3::ReconfigParamsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3::ReconfigParamsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task3::ReconfigParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "099e3b9abed354a4764ac4b1311c2531";
  }

  static const char* value(const ::task3::ReconfigParamsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x099e3b9abed354a4ULL;
  static const uint64_t static_value2 = 0x764ac4b1311c2531ULL;
};

template<class ContainerAllocator>
struct DataType< ::task3::ReconfigParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task3/ReconfigParamsRequest";
  }

  static const char* value(const ::task3::ReconfigParamsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task3::ReconfigParamsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string param_name\n\
float64 param_val\n\
";
  }

  static const char* value(const ::task3::ReconfigParamsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task3::ReconfigParamsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.param_name);
      stream.next(m.param_val);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReconfigParamsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task3::ReconfigParamsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task3::ReconfigParamsRequest_<ContainerAllocator>& v)
  {
    s << indent << "param_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.param_name);
    s << indent << "param_val: ";
    Printer<double>::stream(s, indent + "  ", v.param_val);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK3_MESSAGE_RECONFIGPARAMSREQUEST_H
