// Generated by gencpp from file task3/RingApproachPointResponse.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_RINGAPPROACHPOINTRESPONSE_H
#define TASK3_MESSAGE_RINGAPPROACHPOINTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task3
{
template <class ContainerAllocator>
struct RingApproachPointResponse_
{
  typedef RingApproachPointResponse_<ContainerAllocator> Type;

  RingApproachPointResponse_()
    : output_x(0.0)
    , output_y(0.0)
    , output_z(0.0)
    , output_w(0.0)  {
    }
  RingApproachPointResponse_(const ContainerAllocator& _alloc)
    : output_x(0.0)
    , output_y(0.0)
    , output_z(0.0)
    , output_w(0.0)  {
  (void)_alloc;
    }



   typedef double _output_x_type;
  _output_x_type output_x;

   typedef double _output_y_type;
  _output_y_type output_y;

   typedef double _output_z_type;
  _output_z_type output_z;

   typedef double _output_w_type;
  _output_w_type output_w;





  typedef boost::shared_ptr< ::task3::RingApproachPointResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task3::RingApproachPointResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RingApproachPointResponse_

typedef ::task3::RingApproachPointResponse_<std::allocator<void> > RingApproachPointResponse;

typedef boost::shared_ptr< ::task3::RingApproachPointResponse > RingApproachPointResponsePtr;
typedef boost::shared_ptr< ::task3::RingApproachPointResponse const> RingApproachPointResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task3::RingApproachPointResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task3::RingApproachPointResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace task3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'task3': ['/home/miha/Desktop/ris-alpha/workspaces/tasks/src/task3/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::task3::RingApproachPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3::RingApproachPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task3::RingApproachPointResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task3::RingApproachPointResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3::RingApproachPointResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3::RingApproachPointResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task3::RingApproachPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d5d6e6db05e5f8fa78eb351c0a546a0";
  }

  static const char* value(const ::task3::RingApproachPointResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d5d6e6db05e5f8fULL;
  static const uint64_t static_value2 = 0xa78eb351c0a546a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::task3::RingApproachPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task3/RingApproachPointResponse";
  }

  static const char* value(const ::task3::RingApproachPointResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task3::RingApproachPointResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 output_x\n\
float64 output_y\n\
float64 output_z\n\
float64 output_w\n\
";
  }

  static const char* value(const ::task3::RingApproachPointResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task3::RingApproachPointResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output_x);
      stream.next(m.output_y);
      stream.next(m.output_z);
      stream.next(m.output_w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RingApproachPointResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task3::RingApproachPointResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task3::RingApproachPointResponse_<ContainerAllocator>& v)
  {
    s << indent << "output_x: ";
    Printer<double>::stream(s, indent + "  ", v.output_x);
    s << indent << "output_y: ";
    Printer<double>::stream(s, indent + "  ", v.output_y);
    s << indent << "output_z: ";
    Printer<double>::stream(s, indent + "  ", v.output_z);
    s << indent << "output_w: ";
    Printer<double>::stream(s, indent + "  ", v.output_w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK3_MESSAGE_RINGAPPROACHPOINTRESPONSE_H
