// Generated by gencpp from file task3/RingApproachPoint.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_RINGAPPROACHPOINT_H
#define TASK3_MESSAGE_RINGAPPROACHPOINT_H

#include <ros/service_traits.h>


#include <task3/RingApproachPointRequest.h>
#include <task3/RingApproachPointResponse.h>


namespace task3
{

struct RingApproachPoint
{

typedef RingApproachPointRequest Request;
typedef RingApproachPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RingApproachPoint
} // namespace task3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3::RingApproachPoint > {
  static const char* value()
  {
    return "a0a873596cba774a4f04b2ea2ebf3221";
  }

  static const char* value(const ::task3::RingApproachPoint&) { return value(); }
};

template<>
struct DataType< ::task3::RingApproachPoint > {
  static const char* value()
  {
    return "task3/RingApproachPoint";
  }

  static const char* value(const ::task3::RingApproachPoint&) { return value(); }
};


// service_traits::MD5Sum< ::task3::RingApproachPointRequest> should match 
// service_traits::MD5Sum< ::task3::RingApproachPoint > 
template<>
struct MD5Sum< ::task3::RingApproachPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3::RingApproachPoint >::value();
  }
  static const char* value(const ::task3::RingApproachPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::RingApproachPointRequest> should match 
// service_traits::DataType< ::task3::RingApproachPoint > 
template<>
struct DataType< ::task3::RingApproachPointRequest>
{
  static const char* value()
  {
    return DataType< ::task3::RingApproachPoint >::value();
  }
  static const char* value(const ::task3::RingApproachPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3::RingApproachPointResponse> should match 
// service_traits::MD5Sum< ::task3::RingApproachPoint > 
template<>
struct MD5Sum< ::task3::RingApproachPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3::RingApproachPoint >::value();
  }
  static const char* value(const ::task3::RingApproachPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::RingApproachPointResponse> should match 
// service_traits::DataType< ::task3::RingApproachPoint > 
template<>
struct DataType< ::task3::RingApproachPointResponse>
{
  static const char* value()
  {
    return DataType< ::task3::RingApproachPoint >::value();
  }
  static const char* value(const ::task3::RingApproachPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_MESSAGE_RINGAPPROACHPOINT_H
