// Generated by gencpp from file task3/TerminalApproach.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_TERMINALAPPROACH_H
#define TASK3_MESSAGE_TERMINALAPPROACH_H

#include <ros/service_traits.h>


#include <task3/TerminalApproachRequest.h>
#include <task3/TerminalApproachResponse.h>


namespace task3
{

struct TerminalApproach
{

typedef TerminalApproachRequest Request;
typedef TerminalApproachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TerminalApproach
} // namespace task3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3::TerminalApproach > {
  static const char* value()
  {
    return "fe183daa6c268d4e2a978bceb0e5896f";
  }

  static const char* value(const ::task3::TerminalApproach&) { return value(); }
};

template<>
struct DataType< ::task3::TerminalApproach > {
  static const char* value()
  {
    return "task3/TerminalApproach";
  }

  static const char* value(const ::task3::TerminalApproach&) { return value(); }
};


// service_traits::MD5Sum< ::task3::TerminalApproachRequest> should match 
// service_traits::MD5Sum< ::task3::TerminalApproach > 
template<>
struct MD5Sum< ::task3::TerminalApproachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3::TerminalApproach >::value();
  }
  static const char* value(const ::task3::TerminalApproachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::TerminalApproachRequest> should match 
// service_traits::DataType< ::task3::TerminalApproach > 
template<>
struct DataType< ::task3::TerminalApproachRequest>
{
  static const char* value()
  {
    return DataType< ::task3::TerminalApproach >::value();
  }
  static const char* value(const ::task3::TerminalApproachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3::TerminalApproachResponse> should match 
// service_traits::MD5Sum< ::task3::TerminalApproach > 
template<>
struct MD5Sum< ::task3::TerminalApproachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3::TerminalApproach >::value();
  }
  static const char* value(const ::task3::TerminalApproachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::TerminalApproachResponse> should match 
// service_traits::DataType< ::task3::TerminalApproach > 
template<>
struct DataType< ::task3::TerminalApproachResponse>
{
  static const char* value()
  {
    return DataType< ::task3::TerminalApproach >::value();
  }
  static const char* value(const ::task3::TerminalApproachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_MESSAGE_TERMINALAPPROACH_H
