// Generated by gencpp from file task3/TreasureLocator.msg
// DO NOT EDIT!


#ifndef TASK3_MESSAGE_TREASURELOCATOR_H
#define TASK3_MESSAGE_TREASURELOCATOR_H

#include <ros/service_traits.h>


#include <task3/TreasureLocatorRequest.h>
#include <task3/TreasureLocatorResponse.h>


namespace task3
{

struct TreasureLocator
{

typedef TreasureLocatorRequest Request;
typedef TreasureLocatorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TreasureLocator
} // namespace task3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task3::TreasureLocator > {
  static const char* value()
  {
    return "f8ab16647b43984ab945118af6794cb3";
  }

  static const char* value(const ::task3::TreasureLocator&) { return value(); }
};

template<>
struct DataType< ::task3::TreasureLocator > {
  static const char* value()
  {
    return "task3/TreasureLocator";
  }

  static const char* value(const ::task3::TreasureLocator&) { return value(); }
};


// service_traits::MD5Sum< ::task3::TreasureLocatorRequest> should match 
// service_traits::MD5Sum< ::task3::TreasureLocator > 
template<>
struct MD5Sum< ::task3::TreasureLocatorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task3::TreasureLocator >::value();
  }
  static const char* value(const ::task3::TreasureLocatorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::TreasureLocatorRequest> should match 
// service_traits::DataType< ::task3::TreasureLocator > 
template<>
struct DataType< ::task3::TreasureLocatorRequest>
{
  static const char* value()
  {
    return DataType< ::task3::TreasureLocator >::value();
  }
  static const char* value(const ::task3::TreasureLocatorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task3::TreasureLocatorResponse> should match 
// service_traits::MD5Sum< ::task3::TreasureLocator > 
template<>
struct MD5Sum< ::task3::TreasureLocatorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task3::TreasureLocator >::value();
  }
  static const char* value(const ::task3::TreasureLocatorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task3::TreasureLocatorResponse> should match 
// service_traits::DataType< ::task3::TreasureLocator > 
template<>
struct DataType< ::task3::TreasureLocatorResponse>
{
  static const char* value()
  {
    return DataType< ::task3::TreasureLocator >::value();
  }
  static const char* value(const ::task3::TreasureLocatorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK3_MESSAGE_TREASURELOCATOR_H
