(cl:defpackage alpha1-srv
  (:use )
  (:export
   "MULTINTEGERS"
   "<MULTINTEGERS-REQUEST>"
   "MULTINTEGERS-REQUEST"
   "<MULTINTEGERS-RESPONSE>"
   "MULTINTEGERS-RESPONSE"
   "SUMINTEGERS"
   "<SUMINTEGERS-REQUEST>"
   "SUMINTEGERS-REQUEST"
   "<SUMINTEGERS-RESPONSE>"
   "SUMINTEGERS-RESPONSE"
  ))

