(cl:defpackage task1-srv
  (:use )
  (:export
   "CHECKPOINTPROCESSOR"
   "<CHECKPOINTPROCESSOR-REQUEST>"
   "CHECKPOINTPROCESSOR-REQUEST"
   "<CHECKPOINTPROCESSOR-RESPONSE>"
   "CHECKPOINTPROCESSOR-RESPONSE"
   "CHECKPOINT_RES"
   "<CHECKPOINT_RES-REQUEST>"
   "CHECKPOINT_RES-REQUEST"
   "<CHECKPOINT_RES-RESPONSE>"
   "CHECKPOINT_RES-RESPONSE"
   "ELLIPSELOCATOR"
   "<ELLIPSELOCATOR-REQUEST>"
   "ELLIPSELOCATOR-REQUEST"
   "<ELLIPSELOCATOR-RESPONSE>"
   "ELLIPSELOCATOR-RESPONSE"
  ))

