(cl:defpackage task2-msg
  (:use )
  (:export
   "<APPROACHIMAGEFEEDBACK>"
   "APPROACHIMAGEFEEDBACK"
   "<RINGDATA>"
   "RINGDATA"
   "<TERMINALAPPROACHFEEDBACK>"
   "TERMINALAPPROACHFEEDBACK"
   "<VALIDREGIONSMAPRESPONSE>"
   "VALIDREGIONSMAPRESPONSE"
  ))

