(cl:defpackage task2-msg
  (:use )
  (:export
   "<APPROACHIMAGEFEEDBACK>"
   "APPROACHIMAGEFEEDBACK"
   "<RINGAPPROACHPOINTRESPONSE>"
   "RINGAPPROACHPOINTRESPONSE"
   "<SAYCOMMAND>"
   "SAYCOMMAND"
   "<TERMINALAPPROACHFEEDBACK>"
   "TERMINALAPPROACHFEEDBACK"
   "<VALIDREGIONSMAPRESPONSE>"
   "VALIDREGIONSMAPRESPONSE"
  ))

